- name: install nginx and run
  hosts: web
  become: yes  #sudo access
  tasks: # install nginx and run on the server
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
