- name: install nginx and run
  hosts: web
  become: yes  #sudo access
  tasks: # install nginx and run on the server
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

- name: run nginx
  hosts: web
  become: yes
  tasks: #run nginx
   - name: run nginx
     ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
