- name: variable
  hosts: web
  vars: 
    COURSE: "DEVOPS with AWS"
    DURATION: "90 days"
  become: yes
  tasks:
    - name: print the variable
      ansible.builtin.debug:
        msg: " Hi This is ramesh, learning {{COURSE}} and duration {{DURATION}}"

    - name: print the variable 2
      vars: 
          COMPANY: "TOYOTA MOTOR EUROPE"
          POSITION: "Technology lead"
      ansible.builtin.debug:
          msg: " Hi This is ramesh, working in {{COMPANY}} and my position is {{POSITION}}"

    - name: print the variable again and again
      ansible.builtin.debug:
        msg: " Hi This is ramesh, learning {{COURSE}} and duration {{DURATION}}"

      
  
    