- name: variables with input file
  hosts: web
  var_files:
    -vars.yaml
  tasks:
    - name: variable with input file
      ansible.builtin.debug:
        msg: " Hi This is ramesh, learning {{COURSE}} and duration {{DURATION}}"
    
    - name: variable with input files message 2
      anisble.builtin.debug:
        msg: " Hi This is ramesh, Working at {{Toyota Motor Europe}} and position is {{POSITION}}"