- name: variables with prompt
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: please enter the course name
      private: false # non confidential
    - name: DURATION
      prompt: please enter the duration
  tasks:
    - name : variables with prompt
      ansible.builtin.debug:
        msg: " Hi This is ramesh, learning {{COURSE}} and duration {{DURATION}}"