- name: write the condition for numbers
  hosts: local
  connection: local
  var_prompt: 
    - name: number
      prompt: please enter the number
  tasks:
- name: Check the number less than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number < 10

- name: Check the number greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater  than or equal to 10"
    when: number >= 10


