- name: install the software on the server
  hosts: web
  become: yes
  tasks:
    - name: install multiple softwares
      ansible.builtin.package:
        name:  "{{item.name}}"
        state:  "{{item.state}}"
        
      loop:
      - { 'name': 'mysql' , 'state': 'present'}
      - { 'name': 'mysql' , 'state': 'absent'}
      - { 'name': 'httpd' , 'state': 'present'}