- name: filter and functions
  hosts:  local
  connection: local
  tasks:
    - name: print the course name
      ansible.builtin.debug:
        msg: " Course name is {{ course| default('Ansible')}} "