- name: filter and functions
  hosts:  local
  connection: local
  tasks:
    - name: print the course name
      ansible.builtin.debug:
        msg: " Course name is {{ course| default('Ansible')}} "

    - name: print the upper case
      vars:
        greeting: "hello Ramesh"
      ansible.builtin.debug:
        msg: " {{greeting | upper }} "
    
    - name: print the lower case
      vars:
        greeting: "hello Ramesh"
      ansible.builtin.debug:
        msg: " {{greeting | lower }} "
    
      
    - name: print the unique number
      vars:
        numbers: [ 1,2,45,37,57,139,3, 2,1 ]
      ansible.builtin.debug:
        msg: " {{ numbers | unique }} "
    
      
    - name: print the unique number
      vars:
        numbers: [ 1,2,45,37,57,139,3, 2,1 ]
      ansible.builtin.debug:
        msg: "min : {{ numbers | min }}  max : {{ numbers | max }} "
    
    - name: print the unique number
      vars:
          COURSE: "Devops"
          Duration: "90 days"
      ansible.builtin.debug:
          msg: "{{COURSE | dict2tems}}"
      