- name: filter and functions
  hosts:  local
  connection: local
  tasks:
    - name: print the course name
      ansible.builtin.debug:
        msg: " Course name is {{ course| default('Ansible')}} "

    - name: print the upper case
      vars:
        greeting: "hello Ramesh"
      ansible.builtin.debug:
        msg: " {{greeting | upper }} "
    
    - name: print the lower case
      vars:
        greeting: "hello Ramesh"
      ansible.builtin.debug:
        msg: " {{greeting | lower }} "