- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    sg_id: "sg-02641bad302eb8ebb"
    ami_id: "ami-09c813fb71547fc4f"
    subnet_id: "subnet-0804c53eefd80a4b1"
    instances:
      - mysql
      - frontend
      - backed
    zone: crazymonk@online
  tasks:
    - name: create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{item}}"
        instance_type: "t2.micro"
        security_group: "{{sg_id}}"
        vpc_subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances
    
    - name: print the output
      ansible.builtin.debug:
        msg: "{{ec2_instances}}"
    
    
    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}" 
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
     
    
    
